# Generated by Django 6.0.1 on 2026-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_contact_type'),
        ),
    ]
