# Generated by Django 6.0.1 on 2026-02-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value'),
        ),
    ]
