# Generated by Django 5.2.10 on 2026-03-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_contact_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.CharField(max_length=255, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Phone"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="Message"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("chatbot", "Chatbot"), ("form", "Contact Form")],
                        default="chatbot",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Received at"),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
