# Generated by Django 6.0.1 on 2026-01-31 19:32

from django.db import migrations


def create_initial_contacts(apps, schema_editor):
    """Создание начальных пустых контактов всех типов"""
    Contact = apps.get_model('main', 'Contact')
    
    contact_types = [
        ('phone', 'Телефон', 1),
        ('email', 'Email', 2),
        ('telegram', 'Telegram', 3),
        ('instagram', 'Instagram', 4),
        ('whatsapp', 'WhatsApp', 5),
        ('facebook', 'Facebook', 6),
        ('linkedin', 'LinkedIn', 7),
    ]
    
    for contact_type, _, order in contact_types:
        Contact.objects.get_or_create(
            type=contact_type,
            defaults={
                'value': '',
                'order': order,
                'is_active': True,
            }
        )


def reverse_contacts(apps, schema_editor):
    """Откат - удаление всех контактов"""
    Contact = apps.get_model('main', 'Contact')
    Contact.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_unique_contact_type'),
    ]

    operations = [
        migrations.RunPython(create_initial_contacts, reverse_contacts),
    ]
