# Generated by Django 6.0.1 on 2026-01-31 19:48

from django.db import migrations


def create_initial_pages(apps, schema_editor):
    """Создание начальных пустых страниц"""
    Page = apps.get_model('main', 'Page')
    
    pages = [
        {
            'slug': 'about',
            'title': 'О компании',
            'content': '',
        },
        {
            'slug': 'how-we-work',
            'title': 'Как мы работаем',
            'content': '',
        },
    ]
    
    for page_data in pages:
        Page.objects.get_or_create(
            slug=page_data['slug'],
            defaults={
                'title': page_data['title'],
                'content': page_data['content'],
                'is_published': True,
            }
        )


def reverse_pages(apps, schema_editor):
    """Откат - удаление страниц"""
    Page = apps.get_model('main', 'Page')
    Page.objects.filter(slug__in=['about', 'how-we-work']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20260131_1932'),
    ]

    operations = [
        migrations.RunPython(create_initial_pages, reverse_pages),
    ]
