# Generated by Django 5.2.10 on 2026-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="value",
            field=models.CharField(
                blank=True,
                help_text="Telegram: числовой chat_id (после /start бота). Ссылка t.me/+телефон для уведомлений не подходит.",
                max_length=255,
                null=True,
                verbose_name="Value",
            ),
        ),
    ]
